#ifndef SERVO_PWM_H
#define SERVO_PWM_H
#include "include/chopper/servo/Easing.h"

#define MAESTRO_BODY_NECK_A_MIN         2032
#define MAESTRO_BODY_NECK_A_MAX         2256
#define MAESTRO_BODY_NECK_A_NEUTRAL     2256
#define MAESTRO_BODY_NECK_A_SPEED       0.0f
#define MAESTRO_BODY_NECK_A_ACCEL       0.0f
#define MAESTRO_BODY_NECK_A_MANUAL      true

#define MAESTRO_BODY_NECK_B_MIN         1952
#define MAESTRO_BODY_NECK_B_MAX         2176
#define MAESTRO_BODY_NECK_B_NEUTRAL     2176
#define MAESTRO_BODY_NECK_B_SPEED       0.0f
#define MAESTRO_BODY_NECK_B_ACCEL       0.0f
#define MAESTRO_BODY_NECK_B_MANUAL      true

#define MAESTRO_BODY_NECK_C_MIN         2048
#define MAESTRO_BODY_NECK_C_MAX         2272
#define MAESTRO_BODY_NECK_C_NEUTRAL     2272
#define MAESTRO_BODY_NECK_C_SPEED       0.0f
#define MAESTRO_BODY_NECK_C_ACCEL       0.0f
#define MAESTRO_BODY_NECK_C_MANUAL      true

#define MAESTRO_UTILITY_ARM_MIN         1264
#define MAESTRO_UTILITY_ARM_MAX         2384
#define MAESTRO_UTILITY_ARM_NEUTRAL     1264
#define MAESTRO_UTILITY_ARM_SPEED       0.0f
#define MAESTRO_UTILITY_ARM_ACCEL       0.0f
#define MAESTRO_UTILITY_ARM_EASING      Easing::CubicEaseInOut

#define MAESTRO_BODY_DOOR_RIGHT_MIN     992
#define MAESTRO_BODY_DOOR_RIGHT_MAX     1920
#define MAESTRO_BODY_DOOR_RIGHT_NEUTRAL 1920
#define MAESTRO_BODY_DOOR_RIGHT_SPEED   0.0f
#define MAESTRO_BODY_DOOR_RIGHT_ACCEL   0.0f
#define MAESTRO_BODY_DOOR_RIGHT_EASING  Easing::CubicEaseInOut

#define MAESTRO_BODY_DOOR_LEFT_MIN      1024
#define MAESTRO_BODY_DOOR_LEFT_MAX      1696
#define MAESTRO_BODY_DOOR_LEFT_NEUTRAL  1030
#define MAESTRO_BODY_DOOR_LEFT_SPEED    0.0f
#define MAESTRO_BODY_DOOR_LEFT_ACCEL    0.0f
#define MAESTRO_BODY_DOOR_LEFT_EASING   Easing::CubicEaseInOut

#define MAESTRO_DOME_PERISCOPE_LIFT_MIN     800
#define MAESTRO_DOME_PERISCOPE_LIFT_MAX     1744
#define MAESTRO_DOME_PERISCOPE_LIFT_NEUTRAL 800
#define MAESTRO_DOME_PERISCOPE_LIFT_SPEED   0.0f
#define MAESTRO_DOME_PERISCOPE_LIFT_ACCEL   0.0f
#define MAESTRO_DOME_PERISCOPE_LIFT_EASING  Easing::CubicEaseInOut

#define MAESTRO_DOME_PERISCOPE_SPIN_MIN     496
#define MAESTRO_DOME_PERISCOPE_SPIN_MAX     2496
#define MAESTRO_DOME_PERISCOPE_SPIN_NEUTRAL 1282
#define MAESTRO_DOME_PERISCOPE_SPIN_SPEED   0.0f
#define MAESTRO_DOME_PERISCOPE_SPIN_ACCEL   0.0f
#define MAESTRO_DOME_PERISCOPE_SPIN_EASING  Easing::CubicEaseInOut

#define MAESTRO_DOME_DOOR_RIGHT_MIN     496
#define MAESTRO_DOME_DOOR_RIGHT_MAX     2304
#define MAESTRO_DOME_DOOR_RIGHT_NEUTRAL 496
#define MAESTRO_DOME_DOOR_RIGHT_SPEED   0.0f
#define MAESTRO_DOME_DOOR_RIGHT_ACCEL   0.0f
#define MAESTRO_DOME_DOOR_RIGHT_EASING  Easing::CubicEaseInOut

#define MAESTRO_DOME_DOOR_LEFT_MIN     576
#define MAESTRO_DOME_DOOR_LEFT_MAX     2496
#define MAESTRO_DOME_DOOR_LEFT_NEUTRAL 2496
#define MAESTRO_DOME_DOOR_LEFT_SPEED   0.0f
#define MAESTRO_DOME_DOOR_LEFT_ACCEL   0.0f
#define MAESTRO_DOME_DOOR_LEFT_EASING  Easing::CubicEaseInOut


#endif // SERVO_PWM_H