#ifndef __SERVO_PIN_MAP_H__
#define __SERVO_PIN_MAP_H__

#define PIN_MAESTRO_CHANNEL_1           0
#define PIN_MAESTRO_CHANNEL_2           1
#define PIN_MAESTRO_CHANNEL_3           2
#define PIN_MAESTRO_CHANNEL_4           3
#define PIN_MAESTRO_CHANNEL_5           4
#define PIN_MAESTRO_CHANNEL_6           5
#define PIN_MAESTRO_CHANNEL_7           6
#define PIN_MAESTRO_CHANNEL_8           7
#define PIN_MAESTRO_CHANNEL_9           8
#define PIN_MAESTRO_CHANNEL_10          9
#define PIN_MAESTRO_CHANNEL_11          10
#define PIN_MAESTRO_CHANNEL_12          11
#define PIN_MAESTRO_CHANNEL_13          12
#define PIN_MAESTRO_CHANNEL_14          13
#define PIN_MAESTRO_CHANNEL_15          14
#define PIN_MAESTRO_CHANNEL_16          15
#define PIN_MAESTRO_CHANNEL_17          16
#define PIN_MAESTRO_CHANNEL_18          17
#define PIN_MAESTRO_CHANNEL_19          18
#define PIN_MAESTRO_CHANNEL_20          19
#define PIN_MAESTRO_CHANNEL_21          20
#define PIN_MAESTRO_CHANNEL_22          21
#define PIN_MAESTRO_CHANNEL_23          22
#define PIN_MAESTRO_CHANNEL_24          23

#define MAESTRO_BODY_NECK_A             PIN_MAESTRO_CHANNEL_1
#define MAESTRO_BODY_NECK_B             PIN_MAESTRO_CHANNEL_2
#define MAESTRO_BODY_NECK_C             PIN_MAESTRO_CHANNEL_3
#define MAESTRO_UTILITY_ARM             PIN_MAESTRO_CHANNEL_4
#define MAESTRO_BODY_DOOR_RIGHT         PIN_MAESTRO_CHANNEL_5
#define MAESTRO_BODY_DOOR_LEFT          PIN_MAESTRO_CHANNEL_6

#define MAESTRO_DOME_PERISCOPE_LIFT     PIN_MAESTRO_CHANNEL_1
#define MAESTRO_DOME_PERISCOPE_SPIN     PIN_MAESTRO_CHANNEL_2

#define MAESTRO_DOME_DOOR_LEFT          PIN_MAESTRO_CHANNEL_3
#define MAESTRO_DOME_ARM_LEFT_LIFT      PIN_MAESTRO_CHANNEL_4
#define MAESTRO_DOME_ARM_LEFT_EXTEND    PIN_MAESTRO_CHANNEL_5
#define MAESTRO_DOME_ARM_LEFT_ROTATE    PIN_MAESTRO_CHANNEL_6

#define MAESTRO_DOME_DOOR_RIGHT         PIN_MAESTRO_CHANNEL_7
#define MAESTRO_DOME_ARM_RIGHT_LIFT     PIN_MAESTRO_CHANNEL_8
#define MAESTRO_DOME_ARM_RIGHT_EXTEND   PIN_MAESTRO_CHANNEL_9
#define MAESTRO_DOME_ARM_RIGHT_ROTATE   PIN_MAESTRO_CHANNEL_10

#define MAESTRO_BODY_CHANNELS           6
#define MAESTRO_DOME_CHANNELS           11

#endif
