#ifndef SERVO_PWM_H
#define SERVO_PWM_H

#define MAESTRO_BODY_ARM_NEURAL 6000
#define MAESTRO_BODY_ARM_MIN 4000
#define MAESTRO_BODY_ARM_MAX 8000

#define MAESTRO_BODY_NOD_A_MIN 4000
#define MAESTRO_BODY_NOD_A_MAX 8000

#define MAESTRO_BODY_NOD_B_MIN 4000
#define MAESTRO_BODY_NOD_B_MAX 8000

#define MAESTRO_BODY_NOD_C_MIN 4000
#define MAESTRO_BODY_NOD_C_MAX 8000

#endif // SERVO_PWM_H