#ifndef SERVO_PWM_H
#define SERVO_PWM_H

#define MAESTRO_BODY_NECK_A_MIN         2048
#define MAESTRO_BODY_NECK_A_MAX         2272
#define MAESTRO_BODY_NECK_A_NEUTRAL     2250

#define MAESTRO_BODY_NECK_B_MIN         1936
#define MAESTRO_BODY_NECK_B_MAX         2192
#define MAESTRO_BODY_NECK_B_NEUTRAL     2180

#define MAESTRO_BODY_NECK_C_MIN         2064
#define MAESTRO_BODY_NECK_C_MAX         2288
#define MAESTRO_BODY_NECK_C_NEUTRAL     2270

#define MAESTRO_UTILITY_ARM_MIN         1264
#define MAESTRO_UTILITY_ARM_MAX         2384
#define MAESTRO_UTILITY_ARM_NEUTRAL     1264
#define MAESTRO_UTILITY_ARM_SPEED       0
#define MAESTRO_UTILITY_ARM_ACCEL       0

#define MAESTRO_BODY_DOOR_RIGHT_MIN     992
#define MAESTRO_BODY_DOOR_RIGHT_MAX     1920
#define MAESTRO_BODY_DOOR_RIGHT_NEUTRAL 1920

#define MAESTRO_BODY_DOOR_LEFT_MIN      1024
#define MAESTRO_BODY_DOOR_LEFT_MAX      1696
#define MAESTRO_BODY_DOOR_LEFT_NEUTRAL  1030

#endif // SERVO_PWM_H