#ifndef __SETTINGS_SYSTEM_H__
#define __SETTINGS_SYSTEM_H__

// Sabertooth Settings
#define SABERTOOTH_SERIAL_BAUD_RATE     9600
#define SABERTOOTH_TANK_DRIVE_ID        129
#define SABERTOOTH_DOME_DRIVE_ID        128

// Maestro Settings
#define MAESTRO_SERIAL_BAUD_RATE        9600

// OpemMV Settings
// TODO: is this fast enough for images?
#define OPENMV_SERIAL_BAUD_RATE         115200

// MP3 Trigger Settings
#define MP3TRIGGER_SERIAL_BAUD_RATE     38400
#define MP3TRIGGER_DEFAULT_VOLUME       50

// Controller settings
#define CONTROLLER_JOYSTICK_MAX_INPUT  512
#define CONTROLLER_JOYSTICK_MIN_INPUT  -512
#define CONTROLLER_JOYSTICK_MAX_OUTPUT 1.0
#define CONTROLLER_JOYSTICK_MIN_OUTPUT -1.0


// Debug statements
#define DEBUG_DRIVE_MOTOR                 true
#define DEBUG_DOME_MOTOR                  true

#include <Bluepad32.h>
#define DEBUG_PRINTLN(s) Console.println(s)
#define DEBUG_PRINT(s) Console.print(s)
#define DEBUG_PRINTF(...) Console.printf(__VA_ARGS__)
#define DEBUG_PRINTLN_HEX(s) Console.println(s,HEX)
#define DEBUG_PRINT_HEX(s) Console.print(s,HEX)
#define DEBUG_FLUSH() Console.flush()

#define DRIVE_DEBUG_PRINTLN(s) if (DEBUG_DRIVE_MOTOR) { DEBUG_PRINTLN(s); }
#define DRIVE_DEBUG_PRINT(s) if (DEBUG_DRIVE_MOTOR) { DEBUG_PRINT(s); }
#define DRIVE_DEBUG_PRINTF(...) if (DEBUG_DRIVE_MOTOR) { DEBUG_PRINTF(__VA_ARGS__); }
#define DRIVE_DEBUG_PRINTLN_HEX(s) if (DEBUG_DRIVE_MOTOR) { DEBUG_PRINTLN_HEX(s,HEX); }
#define DRIVE_DEBUG_PRINT_HEX(s) if (DEBUG_DRIVE_MOTOR) { DEBUG_PRINT_HEX(s,HEX); }
#define DRIVE_DEBUG_FLUSH() if (DEBUG_DRIVE_MOTOR) { DEBUG_FLUSH(); }

#define DOME_DEBUG_PRINTLN(s) if (DEBUG_DOME_MOTOR) { DEBUG_PRINTLN(s); }
#define DOME_DEBUG_PRINT(s) if (DEBUG_DOME_MOTOR) { DEBUG_PRINT(s); }
#define DOME_DEBUG_PRINTF(...) if (DEBUG_DOME_MOTOR) { DEBUG_PRINTF(__VA_ARGS__); }
#define DOME_DEBUG_PRINTLN_HEX(s) if (DEBUG_DOME_MOTOR) { DEBUG_PRINTLN_HEX(s,HEX); }
#define DOME_DEBUG_PRINT_HEX(s) if (DEBUG_DOME_MOTOR) { DEBUG_PRINT_HEX(s,HEX); }
#define DOME_DEBUG_FLUSH() if (DEBUG_DOME_MOTOR) { DEBUG_FLUSH(); }

#define MOTOR_DEBUG_PRINTLN(s) if (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR) { DEBUG_PRINTLN(s); }
#define MOTOR_DEBUG_PRINT(s) if (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR) { DEBUG_PRINT(s); }
#define MOTOR_DEBUG_PRINTF(...) if (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR) { DEBUG_PRINTF(__VA_ARGS__); }
#define MOTOR_DEBUG_PRINTLN_HEX(s) if (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR) { DEBUG_PRINTLN_HEX(s,HEX); }
#define MOTOR_DEBUG_PRINT_HEX(s) if (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR) { DEBUG_PRINT_HEX(s,HEX); }
#define MOTOR_DEBUG_FLUSH() if (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR) { DEBUG_FLUSH(); }
#endif
