#ifndef __SETTINGS_SYSTEM_H__
#define __SETTINGS_SYSTEM_H__

// Sabertooth Settings
#define SABERTOOTH_SERIAL_BAUD_RATE     9600
#define SABERTOOTH_TANK_DRIVE_ID        129
#define SABERTOOTH_DOME_DRIVE_ID        128

// Maestro Settings
#define MAESTRO_SERIAL_BAUD_RATE        9600
#define MAESTRO_BODY_ID                 12
#define MAESTRO_DOME_ID                 13

// OpemMV Settings
// TODO: is this fast enough for images?
#define OPENMV_SERIAL_BAUD_RATE         115200

// MP3 Trigger Settings
#define MP3TRIGGER_SERIAL_BAUD_RATE     38400
#define MP3TRIGGER_DEFAULT_VOLUME       50

// Controller settings
#define CONTROLLER_JOYSTICK_MAX_INPUT  512
#define CONTROLLER_JOYSTICK_MIN_INPUT  -CONTROLLER_JOYSTICK_MAX_INPUT
#define CONTROLLER_JOYSTICK_MAX_OUTPUT 1.0f
#define CONTROLLER_JOYSTICK_MIN_OUTPUT -CONTROLLER_JOYSTICK_MAX_OUTPUT

// RSS Mechanism settings
#define RSS_MECHANISM_LIMIT_NORMAL_VECTOR      0.25f

// Debug statements
#define DEBUG_SOUND                    false
#define DEBUG_DRIVE_MOTOR              false
#define DEBUG_DOME_MOTOR               false
#define DEBUG_MOTORS                   false
#define DEBUG_MAESTRO                  false
#define DEBUG_CONTROLLER               true
#define DEBUG_RSS_MACHINE              false

#include <Bluepad32.h>
#define DEBUG_PRINTLN(s) Console.println(s)
#define DEBUG_PRINT(s) Console.print(s)
#define DEBUG_PRINTF(...) Console.printf(__VA_ARGS__)
#define DEBUG_PRINTLN_HEX(s) Console.println(s,HEX)
#define DEBUG_PRINT_HEX(s) Console.print(s,HEX)
#define DEBUG_FLUSH() Console.flush()

#if DEBUG_DRIVE_MOTOR
#define DEBUG_DRIVE_PRINTLN(s) DEBUG_PRINTLN(s);
#define DEBUG_DRIVE_PRINT(s) DEBUG_PRINT(s);
#define DEBUG_DRIVE_PRINTF(...) DEBUG_PRINTF(__VA_ARGS__);
#define DEBUG_DRIVE_PRINTLN_HEX(s) DEBUG_PRINTLN_HEX(s);
#define DEBUG_DRIVE_PRINT_HEX(s) DEBUG_PRINT_HEX(s);
#define DEBUG_DRIVE_FLUSH() DEBUG_FLUSH();
#else
#define DEBUG_DRIVE_PRINTLN(s)
#define DEBUG_DRIVE_PRINT(s)
#define DEBUG_DRIVE_PRINTF(...)
#define DEBUG_DRIVE_PRINTLN_HEX(s)
#define DEBUG_DRIVE_PRINT_HEX(s)
#define DEBUG_DRIVE_FLUSH()
#endif

#if DEBUG_DOME_MOTOR
#define DEBUG_DOME_PRINTLN(s) DEBUG_PRINTLN(s);
#define DEBUG_DOME_PRINT(s) DEBUG_PRINT(s);
#define DEBUG_DOME_PRINTF(...) DEBUG_PRINTF(__VA_ARGS__);
#define DEBUG_DOME_PRINTLN_HEX(s) DEBUG_PRINTLN_HEX(s,HEX);
#define DEBUG_DOME_PRINT_HEX(s) DEBUG_PRINT_HEX(s,HEX);
#define DEBUG_DOME_FLUSH() DEBUG_FLUSH();
#else
#define DEBUG_DOME_PRINTLN(s)
#define DEBUG_DOME_PRINT(s)
#define DEBUG_DOME_PRINTF(...)
#define DEBUG_DOME_PRINTLN_HEX(s)
#define DEBUG_DOME_PRINT_HEX(s)
#define DEBUG_DOME_FLUSH()
#endif

#if DEBUG_MOTORS && (DEBUG_DRIVE_MOTOR || DEBUG_DOME_MOTOR)
#define DEBUG_MOTOR_PRINTLN(s) DEBUG_PRINTLN(s);
#define DEBUG_MOTOR_PRINT(s) DEBUG_PRINT(s);
#define DEBUG_MOTOR_PRINTF(...) DEBUG_PRINTF(__VA_ARGS__);
#define DEBUG_MOTOR_PRINTLN_HEX(s) DEBUG_PRINTLN_HEX(s,HEX);
#define DEBUG_MOTOR_PRINT_HEX(s) DEBUG_PRINT_HEX(s,HEX);
#define DEBUG_MOTOR_FLUSH() DEBUG_FLUSH();
#else
#define DEBUG_MOTOR_PRINTLN(s)
#define DEBUG_MOTOR_PRINT(s)
#define DEBUG_MOTOR_PRINTF(...)
#define DEBUG_MOTOR_PRINTLN_HEX(s)
#define DEBUG_MOTOR_PRINT_HEX(s)
#define DEBUG_MOTOR_FLUSH()
#endif

#if DEBUG_MAESTRO
#define DEBUG_MAESTRO_PRINTLN(s) DEBUG_PRINTLN(s);
#define DEBUG_MAESTRO_PRINT(s) DEBUG_PRINT(s);
#define DEBUG_MAESTRO_PRINTF(...) DEBUG_PRINTF(__VA_ARGS__);
#define DEBUG_MAESTRO_PRINTLN_HEX(s) DEBUG_PRINTLN_HEX(s,HEX);
#define DEBUG_MAESTRO_PRINT_HEX(s) DEBUG_PRINT_HEX(s,HEX);
#define DEBUG_MAESTRO_FLUSH() DEBUG_FLUSH();
#else
#define DEBUG_MAESTRO_PRINTLN(s)
#define DEBUG_MAESTRO_PRINT(s)
#define DEBUG_MAESTRO_PRINTF(...)
#define DEBUG_MAESTRO_PRINTLN_HEX(s)
#define DEBUG_MAESTRO_PRINT_HEX(s)
#define DEBUG_MAESTRO_FLUSH()
#endif

#if DEBUG_CONTROLLER
#define DEBUG_CONTROLLER_PRINTLN(s) DEBUG_PRINTLN(s);
#define DEBUG_CONTROLLER_PRINT(s) DEBUG_PRINT(s);
#define DEBUG_CONTROLLER_PRINTF(...) DEBUG_PRINTF(__VA_ARGS__);
#define DEBUG_CONTROLLER_PRINTLN_HEX(s) DEBUG_PRINTLN_HEX(s,HEX);
#define DEBUG_CONTROLLER_PRINT_HEX(s) DEBUG_PRINT_HEX(s,HEX);
#define DEBUG_CONTROLLER_FLUSH() DEBUG_FLUSH();
#else
#define DEBUG_CONTROLLER_PRINTLN(s)
#define DEBUG_CONTROLLER_PRINT(s)
#define DEBUG_CONTROLLER_PRINTF(...)
#define DEBUG_CONTROLLER_PRINTLN_HEX(s)
#define DEBUG_CONTROLLER_PRINT_HEX(s)
#define DEBUG_CONTROLLER_FLUSH()
#endif

#if DEBUG_RSS_MACHINE
#define DEBUG_RSS_MACHINE_PRINTLN(s) DEBUG_PRINTLN(s);
#define DEBUG_RSS_MACHINE_PRINT(s) DEBUG_PRINT(s);
#define DEBUG_RSS_MACHINE_PRINTF(...) DEBUG_PRINTF(__VA_ARGS__);
#define DEBUG_RSS_MACHINE_PRINTLN_HEX(s) DEBUG_PRINTLN_HEX(s,HEX);
#define DEBUG_RSS_MACHINE_PRINT_HEX(s) DEBUG_PRINT_HEX(s,HEX);
#define DEBUG_RSS_MACHINE_FLUSH() DEBUG_FLUSH();
#else
#define DEBUG_RSS_MACHINE_PRINTLN(s)
#define DEBUG_RSS_MACHINE_PRINT(s)
#define DEBUG_RSS_MACHINE_PRINTF(...)
#define DEBUG_RSS_MACHINE_PRINTLN_HEX(s)
#define DEBUG_RSS_MACHINE_PRINT_HEX(s)
#define DEBUG_RSS_MACHINE_FLUSH()
#endif

#endif
